lzc-sdk-version: "0.1"
name: MIND
package: cloud.lazycat.app.mind
version: 1.4.1
description: 一个简单的自托管提醒应用
homepage: https://github.com/Casvt/MIND
author: Casvt
application:
  subdomain: mind
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://mind.cloud.lazycat.app.mind.lzcapp:8080/
services:
  mind:
    image: registry.lazycat.cloud/czyt/mrcas/mind:d1b407aa5addd1f6
    environment:
      - TZ=Asia/Beijing
    binds:
      - /lzcapp/var/db:/app/db
